languageCode = "en-au"
languageName = "English (Australia)"
displayName = ":flag-au:"
isoCode = "en-AU"
weight = 1
rtl = false

title = "Phonon"
description = "Build with the power of digital cash."
copyright = "&copy; 2023 the Phonon DAO"

dateFormat = "2 January 2006"

[params]
  mainSections = ["updates"]
