# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true

# robots = ""

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  logo = "img/logo.png"
  showTitle = false

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
  copyright = "Phonon DAO. All rights reserved."
  disclaimer = "† This website is maintained by the Phonon DAO. The contents and opinions of this website are those of the Phonon DAO. The Phonon DAO provides links to cryptocurrency exchanges as a service to the public. The Phonon DAO does not warrant that the information provided by these websites is correct, complete, and up-to-date. The Phonon DAO is not responsible for their content and expressly rejects any liability for damages of any kind resulting from the use, reference to, or reliance on any information contained within these websites."

[homepage]
  layout = "custom" # valid options: page, profile, custom
  headline = "Make cryptocurrency portable."
  summary = "Phonon generates and transfers cryptographic keypairs that can only ever exist in one physical location at a time. Use Phonon to send an ERC20 token directly via a text message or QR code, or literally hand someone a card with a BTC on it. Portable cryptocurrency that can move person to person without ever broadcasting to a public network."
  showFeatures = false
  features = [
    { img = "img/interoperable.png", headline = "Interoperable.", summary = "Phonon is cross-chain, right out of the box."},
    { img = "img/no_fees.png", headline = "No Fees.", summary = "Send crypto cross-chain bridges. No gas. No problem."},
    { img = "img/secure.png", headline = "Secure.", summary = "Give any digital asset the properties of cash."},
    { img = "img/p2p.png", headline = "P2P.", summary = "We’re used to transactions being validated by miners or stakers. That’s not how this works. Phonon is peer-to-peer."},
    { img = "img/faster.png", headline = "Faster.", summary = "Capable of near instant transfers, orders of magnitude faster than any exchange, payment rail, across any class of digital asset"},
    { img = "img/scalable.png", headline = "Scalable.", summary = "Phonon is capable of more transactions per second than Visa, Mastercard, Ethereum, and Bitcoin. Combined."},
  ]
  communityHeadline = "Be a part of the community"
  communitySummaryOne = "The best way to stay connected and up-to-date with everything Phonon is to join our Discord. There you can connect directly with the community that builds the future of payment technology."
  communitySummaryTwo = "Bring your interest, and any expertise you have. All skills are relevant--coding, marketing, administration, whatever. Join our community and share your excitement for Phonon!"

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/jpanther/congo/tree/dev/exampleSite/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = false
  showComments = false
  # sharingLinks = ["facebook", "twitter", "mastodon", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = false
  paginationWidth = 100

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[topBanner]
  date = "2023-02-28"
  tagline = "Want to know what we're working on? Watch our monthly update."
  callToAction = "Watch Monthly Update"
  pageRef = "updates"